# Generated by Django 5.0.4 on 2026-04-08 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fighters', '0002_fight_youtube_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('thumbnail_url', models.URLField()),
                ('channel_id', models.CharField(max_length=50)),
                ('published_at', models.DateTimeField()),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_velada', models.BooleanField(default=False)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_quote', models.CharField(blank=True, max_length=300)),
                ('ai_tags', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('published', 'Publicado'), ('rejected', 'Rechazado')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('fighter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='fighters.fighter')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['fighter', 'status', '-published_at'], name='blog_blogpo_fighter_93b39a_idx'), models.Index(fields=['ai_tags'], name='blog_blogpo_ai_tags_cc9d8a_idx')],
            },
        ),
    ]
