# Generated by Django 5.0.4 on 2026-03-19 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fantasy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyleague',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_leagues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaguemember',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.fantasyleague'),
        ),
        migrations.AddField(
            model_name='leaguemember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fantasyleague',
            name='members',
            field=models.ManyToManyField(related_name='leagues', through='fantasy.LeagueMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='leaguemember',
            unique_together={('league', 'user')},
        ),
    ]
