# Generated by Django 5.0.4 on 2026-03-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyleague',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
