FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libpq-dev gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN python manage.py collectstatic --noinput --settings=veladazone.settings.dev
EXPOSE 8000

CMD ["gunicorn", "veladazone.wsgi:application", \
    "--bind", "0.0.0.0:8000", \
    "--workers", "3", \
    "--worker-class", "gthread", \
    "--threads", "2", \
    "--timeout", "120", \
    "--keep-alive", "5", \
    "--max-requests", "1000", \
    "--max-requests-jitter", "100"]
