# Generated by Django 5.0.4 on 2026-04-05 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=200)),
                ('emoji', models.CharField(default='🏅', max_length=8)),
                ('category', models.CharField(choices=[('predicciones', 'Predicciones'), ('debate', 'Debate'), ('social', 'Social'), ('ligas', 'Ligas Fantasy'), ('especial', 'Especial')], max_length=20)),
                ('points', models.PositiveSmallIntegerField(default=10)),
                ('is_secret', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['category', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='achievements.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
