
VELADA_KEYWORDS = [
    "velada",
    "boxeo",
    "pelea",
    "combate",
    "entrenamiento",
    "sparring",
    "ring",
    "guantes",
    "rival",
    "plex",
    "illojuan",
    "grefg",
    "rivers",
    "fernanfloo",
    "perxitaa",
    "momo",
    "luisito",
    "weigh",
    "pesaje",
    "cara a cara",
    "rueda de prensa",
]