# Generated by Django 5.0.4 on 2026-04-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
