# Generated by Django 5.0.4 on 2026-04-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0002_fight_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='channel_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
